AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BPartners Annotator API - Computation and API

Globals:
  Function:
    CodeUri: .
    Runtime: java17
    Tracing: Active
    Architectures:
      - x86_64
    Timeout: 60
    MemorySize: 1024
    AutoPublishAlias: live
    SnapStart:
      ApplyOn: PublishedVersions
    Environment:
      Variables:
        DATABASE_URL: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/db/url}}'
        DATABASE_USERNAME: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/db/username}}'
        DATABASE_PASSWORD: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/db/password}}'
        AWS_SQS_QUEUE_URL: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/sqs/mailbox-queue-url}}'
        AWS_EVENTBRIDGE_BUS: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/eventbridge/bus-name}}'
        AWS_SES_SOURCE: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/ses/source}}'
    VpcConfig:
      SecurityGroupIds:
        - !Sub '{{resolve:ssm:/bpartners/sg/id}}'
      SubnetIds:
        - !Sub '{{resolve:ssm:/bpartners/private/subnet1/id}}'
        - !Sub '{{resolve:ssm:/bpartners/private/subnet2/id}}'

Parameters:
  Env:
    Type: String

Resources:
  BpartnersAnnotatorApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.bpartners.annotator.LambdaHandler::handleRequest
      Role: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/execution/role-arn}}'
      Events:
        ApiCall:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  MailboxEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.bpartners.annotator.MailboxEventHandler::handleRequest
      Role: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/mailbox-execution/role-arn}}'
      Events:
        GetFeatures:
          Type: SQS
          Properties:
            Queue: !Sub '{{resolve:ssm:/bpartners-annotator/${Env}/sqs/mailbox-queue-arn}}'
            BatchSize: 1


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  BpartnersApiAnnotator:
    Description: API Gateway endpoint URL for Prod stage for Bpartners Annotator Api function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
