name: CD Compute

on:
  push:
    branches:
      - 'prod'
      - 'preprod'

  workflow_dispatch:

  workflow_call:

jobs:
  deploy-api:
    if: ${{ github.ref_name == 'prod' || github.ref_name == 'preprod' }}

    runs-on: ubuntu-latest

    timeout-minutes: 45

    env:
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Install AWS SAM cli
        uses: aws-actions/setup-sam@v1

      - name: Configure preprod AWS credentials
        if: ${{ github.ref_name != 'prod' }}
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure prod AWS credentials
        if: ${{ github.ref_name == 'prod' }}
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve S3 Bucket-name for storing package
        id: s3_bucket_name
        run: |
          SSM_PARAMETER_NAME="/bpartners-annotator/${{ github.ref_name }}/deployment-package/s3/bucket-name"
          SSM_PARAMETER_VALUE=$(aws ssm get-parameter --name $SSM_PARAMETER_NAME --query 'Parameter.Value' --output text)
          echo "s3_bucket=$SSM_PARAMETER_VALUE" >> $GITHUB_ENV

      - name: Build application
        run: sam build

      - name: Deploy application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ github.ref_name }}-bpartners-annotator-api --s3-bucket ${{ env.s3_bucket }} --capabilities CAPABILITY_IAM --region ${{ env.AWS_REGION }} --parameter-overrides Env=${{ github.ref_name }}